// Setup wizard — creates .env and providers.yaml on first run.
import fs from 'node:fs';
import path from 'node:path';
import YAML from 'yaml';
import { config } from '../config.js';
import { ask, choose, writeIfMissing } from './prompt.js';

const ENV_TPL = (values) =>
`# OpenCode Gateway — generated by setup wizard
TELEGRAM_BOT_TOKEN=${values.botToken}
TELEGRAM_ALLOWED_USERS=${values.allowedUsers}
TELEGRAM_ADMIN_USERS=${values.adminUsers}

DEFAULT_PROVIDER=${values.defaultProvider}
DEFAULT_MODEL=${values.defaultModel}
DEFAULT_TEMPERATURE=0.7
DEFAULT_MAX_TOKENS=4096

SYSTEM_PROMPT=${values.systemPrompt}

DB_PATH=./data/gateway.db
LOG_LEVEL=info
LOG_FORMAT=pretty

REQUEST_TIMEOUT_MS=120000
VISION_PROVIDER=
VISION_MODEL=
HISTORY_LIMIT=20
MAX_INPUT_CHARS=8000
STREAMING=true
`;

const PROVIDER_TEMPLATES = {
  openai: () => ({
    name: 'openai',
    base_url: 'https://api.openai.com/v1',
    auth_mode: 'header',
    key_env: 'OPENAI_API_KEY',
    models: {
      'gpt-4o-mini': { context: 128000, vision: true },
      'gpt-4o': { context: 128000, vision: true },
    },
  }),
  openrouter: () => ({
    name: 'openrouter',
    base_url: 'https://openrouter.ai/api/v1',
    auth_mode: 'header',
    key_env: 'OPENROUTER_API_KEY',
    models: {
      'anthropic/claude-3.5-sonnet': { context: 200000, vision: true },
    },
  }),
  ollama: () => ({
    name: 'ollama',
    base_url: 'http://localhost:11434/v1',
    auth_mode: 'none',
    key_env: '',
    models: {
      'llama3.2': { context: 128000, vision: false },
    },
  }),
  custom: () => null,
};

export async function setup() {
  console.log('\n🚀 OpenCode Gateway — setup wizard\n');

  if (!process.stdin.isTTY) {
    console.log('Run this from an interactive terminal.');
    process.exit(1);
  }

  const botToken = await ask('Telegram bot token (from @BotFather)', { mask: true, validate: (v) => v.length > 10 || 'Token too short' });
  const adminUsers = await ask('Admin user IDs (comma-separated)', { defaultValue: '' });
  const allowedUsers = await ask('Allowed user IDs (comma-separated, blank = all)', { defaultValue: '' });

  const template = await choose('Pick a default provider template:', Object.keys(PROVIDER_TEMPLATES), 0);

  let provider;
  if (template === 'custom') {
    const name = await ask('Provider name', { defaultValue: 'custom' });
    const base_url = await ask('Base URL', { validate: (v) => /^https?:\/\//.test(v) || 'Must start with http(s)://' });
    const auth_mode = await choose('Auth mode', ['header (Bearer)', 'xheader (x-api-key)', 'query (?key=)', 'body (api_key in JSON)', 'none'], 0);
    const key_env = await ask('Env var holding the key (e.g. MY_API_KEY)', { defaultValue: `${name.toUpperCase().replace(/\W/g, '_')}_API_KEY` });
    const modelId = await ask('First model id', { validate: (v) => !!v });
    provider = {
      name,
      base_url,
      auth_mode: auth_mode.split(' ')[0],
      key_env: auth_mode === 'none' ? '' : key_env,
      models: { [modelId]: { context: 8192, vision: false } },
    };
  } else {
    provider = PROVIDER_TEMPLATES[template]();
  }

  const defaultProvider = provider.name;
  const defaultModel = Object.keys(provider.models)[0];
  const systemPrompt = await ask('Default system prompt', { defaultValue: 'You are a helpful assistant.' });

  const envPath = path.join(config.root, '.env');
  writeIfMissing(envPath, ENV_TPL({
    botToken, adminUsers, allowedUsers,
    defaultProvider, defaultModel, systemPrompt,
  }));
  console.log(`✓ Wrote ${envPath}`);

  if (provider) {
    const providerKeyLine = provider.auth_mode !== 'none' && provider.key_env
      ? `${provider.key_env}=${template === 'custom' ? '' : ''}\n`
      : '';
    if (providerKeyLine) {
      fs.appendFileSync(envPath, `\n${providerKeyLine}`);
    }
  }

  const providersPath = path.join(config.root, 'providers.yaml');
  writeIfMissing(providersPath, YAML.stringify({ providers: [provider] }));
  console.log(`✓ Wrote ${providersPath}`);

  fs.mkdirSync(path.join(config.root, 'data'), { recursive: true });

  console.log('\n✅ Setup complete. Next:');
  console.log('   1. Fill API keys in .env');
  console.log('   2. Run: npm run doctor   (validate + test connectivity)');
  console.log('   3. Run: npm start         (launch the bot)');
}
